version: "3"
services:
  backend:
    build:
      context: .
      dockerfile: dockerfile
    command: uvicorn app:app --port 8000 --reload
    ports:
      - "8000:8000"
    networks:
      - os-dev

networks:
  os-dev:
    external: true
    name: os-dev